# Generated by Django 3.2.18 on 2023-03-28 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeSanitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_sanitarias', to='assistencia_tecnica.distrito')),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='assistencia_tecnica.area')),
            ],
        ),
        migrations.CreateModel(
            name='FichaAssistenciaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(max_length=255)),
                ('nome_provedor', models.CharField(max_length=255)),
                ('problemas_identificados', models.TextField()),
                ('tipo_problema', models.CharField(choices=[('Antigo', 'Antigo'), ('Novo', 'Novo')], max_length=100)),
                ('atcividades_realizar_resolver_problema', models.CharField(max_length=255)),
                ('nome_pessoa_responsavel_resolver', models.CharField(max_length=255)),
                ('email_pessoa_responsavel_resolver', models.CharField(max_length=255)),
                ('prazo', models.DateField()),
                ('nome_beneficiario_at', models.CharField(max_length=255)),
                ('comentarios', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Resolvido', 'Resolvido')], default='Pendente', max_length=255)),
                ('feito_em', models.DateField(auto_now_add=True)),
                ('feito_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to=settings.AUTH_USER_MODEL)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='assistencia_tecnica.indicador')),
                ('unidades_sanitaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='assistencia_tecnica.unidadesanitaria')),
            ],
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distritos', to='assistencia_tecnica.provincia'),
        ),
        migrations.AddField(
            model_name='area',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='assistencia_tecnica.sector'),
        ),
    ]
