# Generated by Django 4.1.7 on 2023-03-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienteligiblevlcollection',
            name='community',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='viralloadtestresult',
            name='community',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
